### ISSUE TITLE
AIC comparable to lm()?

### ISSUE THREAD

**Issue by kkmann** [runehaubo/ordinal#27]
Hey,

just a brief question, is the AIC computed from a clm fit comparable to the AIC obtained from a linear model fitted with lm? Would be nice to clarify that in the docs.

Best,

Kevin

**Comment by runehaubo** [comment]
The short answer is no, not directly. The problem is that the log-likelihoods are on different scales - however, they can be linked by considering the following way of writing the log-likelihood (taken from an unpublished note that I wrote a few years back):
<img width="580" alt="Screenshot 2020-02-26 at 19 28 44" src="https://user-images.githubusercontent.com/5217453/75375526-87054c00-58ce-11ea-8c56-c249985e18ea.png">

If we observe continuous data we can consider CLMs for binned versions of the data or linear models for the continuous data themselves. If we use a probit link we can even consider a continuum of models from a CLM with flexible thresholds -> a CLM with fixed equidistant thresholds -> a CLM with fixed equidistant thresholds closely spaced corresponding to the precision of the recorded "continuous" outcome -> a LM for the recorded continuous outcome (though of course recorded with finite precision). The note included in the picture above shows that the likelihoods, and therefore AICs, differ only by a constant amount depending only on the precision (epsilon). 

So if you want to compare CLMs and LMs you just have to adjust for the term involving epsilon but as none of this is implemented in user-friendly functions in **ordinal** you likely have to do some programming yourself. 

Note the consequence: A CLM can fit a linear model to any desired accuracy - it can even fit the linear model while taking into account that the observed data are not truly continuous but "only" observed with finite precision and therefore more correctly interval censored data. Also note that a location-scale CLM can be used to fit linear models with a log-linear model for the residual variance. Or that the assumption of normality of the linear model can be challenged by changing the the link function to something other than the probit effectively providing a framework for the so-called location-scale family of models. Who knows, there might actually be R packages implementing this...

Cheers
Rune

**Comment by kkmann** [comment]
Thank you so much for the extensive clarification (and a great and well-documented package in general). Very insightful!
