### ISSUE TITLE
Hessian not positive definite issue

### ISSUE THREAD

**Issue by wma9** [runehaubo/ordinal#5]
Hi, I am using the clm function to fit an model on ordinal rating data, and I keep run into "Hessian is not positive definite", or "Hessian is numerically singular" issue for 70% of my datasets. The model is quite simple, in that there is only one fixed effect, what will you recommend to fix this problem? By the way, is there a way to make it speed up the computation when using clmm? And it would be helpful to understand why hessian is computed when there is no random effect? Thank you very much!

**Comment by runehaubo** [comment]
The Hessian is needed in order to compute standard errors of parameters and to evaluate model identifiability. This is the case for CLMs as well as CLMMs.

If the Hessian is not positive definite or singular it means that there is a problem identifying the model which can be due to issues such as "complete separation" or other types of over-parameterisation. 

More details will be needed for more specific advice.
