### ISSUE TITLE
Incorrect interval estimates in predict.clm()

### ISSUE THREAD

**Issue by MrJerryTAO** [runehaubo/ordinal#54]
Hi @runehaubo, I used your ordinal package intensively lately. I noticed that ordinal:::prob.predict.clm() that generate predicted probability masses may have incorrect components, as its confidence interval is built from only a logistic distribution around a linear predictor while clm() allows a few other distributions. Given the link function, this should be an easy fix.

**Comment by runehaubo** [comment]
I think you are misunderstanding this; please see section 4.8 here https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf. The logit transform is used to get more appropriate confidence intervals rather than simple symmetric ones for the fitted probabilities. This has nothing to do with the link function in the model that produces the fitted probabilities. I'm closing the issue now, but feel free to re-open if I misunderstood you.

Br
Rune
